name: "Uni Vigo"
title: "Everest"
#theme: Everest.css 
description: |
  Everest
output_dir: "docs"
repository_url: https://github.com/fabbiocrux/Uni-Vigo
navbar:
#  logo:
#    image: figures/logo.png
#    href: https://lf2l.github.io/everest-bio/
  search: true
  source_url: true
  right:
    - text: "Article"
      href: index.html
    - text: "Data Analysis"
      #href: 00-References.html    
exclude: ['Datos/', "*.csv"]      
output:
  distill::distill_article:
    toc: true
    toc_depth: 2